---
hpviz_elastic_password: '{{ vault_hpviz_elastic_password }}'

# TLS certificates for this host
hpviz_tls_cert: '{{ vault_hpviz_tls_cert }}'
hpviz_tls_key: '{{ vault_hpviz_tls_key }}'

# virtual hostname for nginx
hpviz_virtual_hostname: "viz001.ecu-sri.net"

# vector
hpviz_vector_hostkey: "viz001_ecu-sri_net"

# rsyslog
hpviz_syslog_ingest_ip: "127.0.0.1"
hpviz_syslog_ingest_port: "514"

# grafana
hpviz_grafana_admin_pass: "{{ vault_hpviz_grafana_admin_pass }}"

# IP Addresses
hpviz_sink_ip: "143.110.158.73"
hpviz_viz_ip: "207.154.249.9"
hpviz_vector_port: "9000"
