---
vault_hpviz_elastic_password: "Terror!5t"

vault_hpviz_grafana_admin_pass: "5tAn)ards"

# IP Addresses
vault_hpviz_sink_ip: "143.110.158.73"
vault_hpviz_viz_ip: "207.154.249.9"

# nifi
vault_hpviz_nifi_admin_user: "hpviz-admin"
vault_hpviz_nifi_admin_pass: "5tAn)ards"

vault_hpviz_tls_cert: |
  -----BEGIN CERTIFICATE-----
  MIIFozCCBIugAwIBAgIJAO9RjcCr2VnHMA0GCSqGSIb3DQEBBQUAMGsxCzAJBgNV
  BAYTAkFVMRowGAYDVQQIExFXZXN0ZXJuIEF1c3RyYWxpYTEQMA4GA1UEChMHRUNV
  LVNSSTEOMAwGA1UECxMFSFBWaXoxHjAcBgNVBAMTFUhQVml6IEludGVybWVkaWF0
  ZSBDQTAeFw0yMDEwMjIwNTQ1MDBaFw0yMTExMjMwNTQ1MDBaMHgxCzAJBgNVBAYT
  AkFVMRowGAYDVQQIDBFXZXN0ZXJuIEF1c3RyYWxpYTEOMAwGA1UEBwwFUGVydGgx
  EDAOBgNVBAoMB0VDVS1TUkkxDjAMBgNVBAsMBUhQVml6MRswGQYDVQQDDBJ2aXow
  MDEuZWN1LXNyaS5uZXQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDL
  5nh4SW/VCaVNOAmd0l+LA9xRNNGthUtXLcn3YyoCiSuxdcVertywxkMpgW40TscN
  gys2f2lYFOyM5WkoFRgZe9+eTIQKSai+liZtXzAuGLEqKRuly2IoZUAW3FDGJdjf
  wei896lIZuTotuTXdaYIE+NPBjBNRBdYvmWUwIkuIrSH0ANetYiqlm8ldYAUGDv9
  lvMusPmz3qAgXV3oCxX/j/7ixaKx44kXgTiDykRmBqK/aV7HpwJavrlfHYy22E2P
  fDJHp8/uhZVYdNSW7TuWKVyeg6p8KiNtbMHk3OZKBTjIAgxBgGhxJ5FUQZjiRx5G
  +++WfQ4p3hXtig5S/2V+jVO1zrtJAA1bMZBIxp5ao2hU2ITotmSVNMS4GWn0wvHg
  WiT+E9DeDcToUoyhxhB+bOOVK4O/TLTu2t+UOs5ZZ2TkzdFhmc8EDG8rZ0LlD4ZC
  eNR+Sya2mdzVgu7qPuI8GWY/5IXFbo1VzYPfsDbE720Cuzf1LTinD8dJkF8SbFZQ
  Zi1YPPnMbSIbTLDxfVw+VLCVVbJWK87liUBjwmeAe7LvA6xukoeAlJtg6Qgk1UQB
  3YsbF9YbTYpcBut5KvT9bLHJQRHXbAJoiFxpBfSdfjKP0UNMlFG42Yr3GCzabF6d
  XnhD6uBbxNftgxKKBEy/pACWBhZIaP82nGMGGG7aZwIDAQABo4IBOzCCATcwCQYD
  VR0TBAIwADARBglghkgBhvhCAQEEBAMCBkAwMwYJYIZIAYb4QgENBCYWJE9wZW5T
  U0wgR2VuZXJhdGVkIFNlcnZlciBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUMxwXo6oV
  Gr7Cut0FkDC+Zf0m4AowgZ0GA1UdIwSBlTCBkoAUn0sdnfHKYVyjOeXLT6jDvqNu
  hX6hd6R1MHMxCzAJBgNVBAYTAkFVMRowGAYDVQQIExFXZXN0ZXJuIEF1c3RyYWxp
  YTEOMAwGA1UEBxMFUGVydGgxEDAOBgNVBAoTB0VDVS1TUkkxDjAMBgNVBAsTBUhQ
  Vml6MRYwFAYDVQQDEw1IUFZpeiBSb290IENBggECMA4GA1UdDwEB/wQEAwIFoDAT
  BgNVHSUEDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQUFAAOCAQEAhjARvka+zHxt
  fh4QU/unx9i9Ed5Z/x4EXxKVrgWHtJjTmXS/dovIp/jr9B3KEQQqIKEoneepIeLG
  wv0nn3BASghKRDjDrYHmdlw8PdIVb54RzEFX14BkWp4TJ7xNISWayg/6pBXc+ZQa
  rLmeRWd2jgU1r6vQDtU7cjHejEVfbO6gooCae+Gw/6u4xPUbuIhXhps6zxcO3sX6
  07kp5fhFnaFBlcaKnuOnAusvc5XD3o7BnVwJJm8gHjqAvwJMv8DHMbElQJ5cwije
  BwwJEf/9G3nKrTa6wodnO/5vqNLGarc2h9fbBCleIpO5UDIqpdVsEOER57sS997b
  8dHkQRvqxg==
  -----END CERTIFICATE-----

vault_hpviz_tls_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEAy+Z4eElv1QmlTTgJndJfiwPcUTTRrYVLVy3J92MqAokrsXXF
  Xq7csMZDKYFuNE7HDYMrNn9pWBTsjOVpKBUYGXvfnkyECkmovpYmbV8wLhixKikb
  pctiKGVAFtxQxiXY38HovPepSGbk6Lbk13WmCBPjTwYwTUQXWL5llMCJLiK0h9AD
  XrWIqpZvJXWAFBg7/ZbzLrD5s96gIF1d6AsV/4/+4sWiseOJF4E4g8pEZgaiv2le
  x6cCWr65Xx2MtthNj3wyR6fP7oWVWHTUlu07lilcnoOqfCojbWzB5NzmSgU4yAIM
  QYBocSeRVEGY4kceRvvvln0OKd4V7YoOUv9lfo1Ttc67SQANWzGQSMaeWqNoVNiE
  6LZklTTEuBlp9MLx4Fok/hPQ3g3E6FKMocYQfmzjlSuDv0y07trflDrOWWdk5M3R
  YZnPBAxvK2dC5Q+GQnjUfksmtpnc1YLu6j7iPBlmP+SFxW6NVc2D37A2xO9tArs3
  9S04pw/HSZBfEmxWUGYtWDz5zG0iG0yw8X1cPlSwlVWyVivO5YlAY8JngHuy7wOs
  bpKHgJSbYOkIJNVEAd2LGxfWG02KXAbreSr0/WyxyUER12wCaIhcaQX0nX4yj9FD
  TJRRuNmK9xgs2mxenV54Q+rgW8TX7YMSigRMv6QAlgYWSGj/NpxjBhhu2mcCAwEA
  AQKCAgEAjdc3usWrTBG3si3nUqiD2lrHKp6JtiHhtTWfJ78N/FGb2YlJ0YHm9/oT
  wo3NMgoTIm065GBh0epMW/9C1aVG7INlneMwf0+aWWpuNOtgwtBefiu2lfETyXIV
  0VFVx2GQqqdj1gCa/EjHuLNyIggvhbMAD3sIotdZPlzEoWQGideOqmOj1ICIH9Mi
  YnaIsHHjWZdmd/aY3e1iiuEocEE1/mAXOX2unfzg4z77J4LPbgHzuR/91PlzA9ll
  bqtJtfBmlAgbmgk89npq1+v97zf8mYsQaRzCvjk6B+b+Qs0ATkGvrELwb6h5/y09
  RdWUGuTKRSsBEjjQX4Ok0WeWa1pLKS332yT3OAK2jYTeEDhYJGe+pu9yCSuBanuf
  TK5Kk3t7O03hSflmQcvWLNDn+9eIwXoNSDieyscdy2flg0kqlhkNulmzOw0Jicgx
  FR8q4BJp94A/2tLP3mVrB1AySOtyn3KWeIaGMfLONWvHN4ECrBZotv6vi+3/GY4E
  07uuFieo3HzRIgSWzAR3JanIaEKZzd3buW5HF1l1mHqZ/0dljI5+RhGMxnVg0WV8
  Tcuj8FwHEbFXfyLzWffWNFkgcmBxbrgNlWPVDQgCF2SoHNYa5GOiQzioI9Xj8ISQ
  a9iXWm522DG8tTCh13WOhHtSd8bN0ArV5yjkLKr2ZAWvLDLP8AECggEBAOtxc3/Q
  0rZoo0QmpXyfWcv5vnz16+IDrVPUVpzX+ggC/hOLI0G9KukEX72RnYX9TOGJiKyv
  CXIO72EQEtn4D+Whdtz2QNHXk1qp0Y/fixCtsXz2oTJ1zXGiyXMN+0NFPLxh35wr
  NtIlzbvvtGyPdBHs3Hpm2IgF24YLy6kpw/DM50PJ7QWdPoGmL8R4xxP7PeK2DG3U
  oorGt50FoaCMPaKVz2lC66vSkg8b3u4u1+dpZfEgpSvlPdnrL0e1yUr/q6Bwf+oI
  PdpSWidt3lUt6zmFSqU0crAkXW0nG932rl21VhjoFIfukZpoM0DbE1ICf1RE/1ma
  hL+5D9lv1aRc/AECggEBAN2z+6QhkJcHpZ0YHts3Ufi2nbxN27l9Ri/VryMFqpmb
  rwZNiGsXd24nrqt7ZlzpYGeiZ9V64XZ4B0hkHMV2nkynuiHKLU05id0SK/DWJKHK
  H9XD2+QbFrNxk/eRGcLvcnJyBlfKqziCCMgpRQO9WBG08o/6UxIvWY2VEtQSias9
  BQ+UT9Z4nbbRSzjl0rqtJ0KFTaGGuSmfpVu+/L9wTUIxdXNKnbgGh0cJGNcGYT7O
  jI7NfSEO/czWDq/AhYq9+Avc8d5fyhQ8gjHmruhkKwnY/0HCTRJNX4IsCc5TCkEf
  xJ+pJTcg3hp0nNXncJ/z8JfvJeGNLJILGIJyQI7ddmcCggEAQOjiQta7gPaQLHXL
  IfR8uTN9RM433fPNkVL1HgCdOiA5FAJEEhepANzn2EeQ+iO/Ul6sg48uN3fOnx/j
  UpyFJXXCY2CwtimMwm4XDGdA27RHPoBwKI05up56k3HDV+R6viTtlQyE7KLneWy4
  fUV/ZoG6tzQrdjTHNMmDuHt/PaAAEjxVUDrtxKigerYhjGyzvxEZlB4PQdtPO8cV
  rEF9rJlIuWhtuM0w32F7sIbRl0cDh9rMLrHgv3eLbWW8vSSHmI/rdAYZp1sU59Hu
  feVO+Gi7D5jKFa2w5CroD+W2ZLddqTgykNdA5STdHIBJb06o8/6ht35WItVOfU/L
  wqiwAQKCAQBejDw74eiU0DkLxtaZ7Hyz0cVxIc8bytYc3kdDa043FhLNYFFWQnq3
  aoruLMEZzJlFeRhJDY+Lg2Kvt6oheBXIYRta/6rULT6jHfXJTrnumZF8C3wCSp8i
  xcQxpxrSbGVlc0VLOW5Nuf7exeLd1mjxnDZ5umqk7baGT9XoxUMa2PoIi9qEf4nb
  BmTLDhARdniwwMK7qQXcP244szl8tvrryMXq9h5O9dHJNJL4WIsuSs3ctLuxVoBc
  U8mNoFATPDLFdGNdz4IRoUBw4Y0kJFvKZlVtiNxvernJfNhtujI8Vbz3zh3F5ely
  ZNrhykLYpCKt2NpR12/zlHHOZ8UqaD3vAoIBADrc4wQn2I7YcE2hEz4OP2G8KBVY
  IGz33A4JJcs1qaBYzzPRElT6NPL983+1C3mGGSBaI7E0MH4jqpFLYXkY5/3+bzde
  RtHuRDN8TWfJIZMhIk0rVlu+88Rb/0mmmi3NsHva/CEgXfiuL8c3HZlsl3xR7vJ0
  9ds4G1QITlWAN0IO7SdLk4Tc01yl/+dZp7dOmLVTI8XMIWFpZcZAG4gMAwD4VjTe
  /om/tH57GZ4CAOKKpJrlvt30xegR0LvBubJWiR1i5qul5GjTEPTiR0/shNpWuCZJ
  6e/7BXrU5oME9HIGh06SWL16iKRSVRtjpiZgszLtCXwzBnmYbWGyEwZKX5g=
  -----END RSA PRIVATE KEY-----
