---
# Base project directory
hpviz_base_dir: /opt/hpviz

#ca_file absolute path
local_ca_file: "/etc/ssl/certs/hpviz-ca-chain-bundle.pem"

# Syslog
hpviz_syslog_ingest_ip: 127.0.0.1
hpviz_syslog_ingest_port: 514
hpviz_vector_to_vector_ingest_port: 9000

# These are users specific to the "sink" group of hosts
#  1) To remove a user from all groups replace the group list with empty string ''
#  2) Removing users change 'state: absent'  all theire directories will eb removed
#  3) pub_key must be present
#  4) all users are created with password login disabled
user_list:
  - username: hpviz-ci
    comment: "WARNING removing this user will break HPViz project CI"
    state: present
    shell: "/bin/bash"
    groups:
      - wheel
    pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsAK7JA+lFIAm9Wnj6x1graKajCi9Sis2M8gwDktRZ8sEPAK7ifFFvkG3T9jDTCnE9FXp6IaLtJlhsg5fqOFcJdwYtadyuCOoTGxL7SrPc5Kze9NbQJYNbXQPc6VQop04Rbj5eeh+kjpr0C8PAPw/lvOksKwIqqvZ5HykdQ7OXiP1WBCaA8bh6hEoi0+zMGem5/hOyWCkqtf3dnUC/2GPbTW8qSBzQxJpaQnMcnw/8dDYEDxQ9FC5m4j8cL/Ol1JIR8f3T5La2T990v18y/LY8JmNF7xsKqec6C2ImWmOKEMlUPUhN8BJLFPgTnAaR3JTVbQHMVukITDNRF+QmTipsUZfQnnnGjwtvuuPqu8ZQjue9itEQBEk7l+aC6ZRfyoEErWLownSDNG3lAqaQb+7qoTwOPrV7/ifeRX/8sEzyQERRaZXbPOv0ZFl2IyCUoq3FXKVlukDBv6zYwEqzQmRlCXK9E4SxCttur9RieGxHiDNEaBG26mvAEnrlpuFWs99SUuh0Jbu+e2bQhL8veR1p3iyLYGZ6YEE/jhe4ViyMlVNEmnrGuuTS229SDpykr+YLKhd42ND7b5WdEL9R47UzzuFdXvkk9Zv7KZ8TgOOwg4xMGmi4LH2phqc8NjxusLwJedmREQSs85YT3zOlHU1g7SIJx1dadRkTUz/XOEPDAQ== hpviz-ci"

  - username: damianw
    comment: "Damian Wernert - added by hpviz-ci"
    shell: "/bin/bash"
    state: present
    pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBP1+PQmRdA6p2oCL9G6HgZHJ4kRwq677bgUiVbouGY4 ed25519-key-20200929"

  - username: wernerz
    comment: "Werner Zietsman - added by hpviz-ci"
    shell: "/bin/bash"
    state: present
    pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMF6Mq096cKysrlgZ9kuvng7yZnnA2uUcPuFw9WY7HLh ed25519-key-20201004"

### Firewall
firewall_services:
  - name: ssh     # <- Do no remove will break CICD
  - name: https
  - name: 522
  - name: 9000

## Managed pip packages to install
pip_install_packages:
  - name: docker
  - name: docker-compose
