---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: no-commit-to-branch
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.5
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: https://github.com/IamTheFij/ansible-pre-commit.git
    rev: v0.1.2
    hooks:
      - id: encryption-check
