---
########################
## common.yml
##
## common playbook for all project hosts
- name: Common Playbook
  hosts: all:!localhost
  gather_facts: yes
  become: True

  pre_tasks:
    - name: check common packages are installed
      package:
        name:
          - kafkacat # command line non jvm kafka cli producer and consumer
          - openjdk-11-jre-headless # required for java keytool
          - ca-certificates
        state: present
      when: ansible_host!="localhost"

    - name: Remove unwanted packages
      package:
        name:
          - syslog-ng
          - librdkafka-dev # library required for syslogng_kafka pip install
        state: absent
      when: ansible_host!="localhost"

    - name: pip self-update
      pip:
        name: pip
        state: latest
      tags:
        - skip_ansible_lint # 403 warning

  roles:
    - role: common_tasks
    - role: geerlingguy.pip
    - role: robertdebock.firewall

  tasks:
    - name: install ca package on system
      apt:
        name: ca-certificates
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      tags:
        - certificates

    - name: copy certificate authority to trusted ca path of the os
      copy:
        src: "files/hpviz-ca-chain-bundle.crt"
        dest: "/usr/local/share/ca-certificates/hpviz-ca-chain-bundle.crt"
        owner: root
        group: root
        mode: 0644
      notify:
        - update trusted ca
      tags:
        - certificates

    - name: Copy public certificate to nginx SSL configuration folder.
      copy:
        content: "{{ hpviz_tls_cert }}"
        dest: "/etc/ssl/certs/{{ hpviz_vector_hostkey }}.crt"
        mode: 0640
        owner: root
        group: root
      notify: restart nginx
      ignore_errors: yes
      tags:
        - certificates

    - name: Copy private key to SSL configuration folder.
      copy:
        content: "{{ hpviz_tls_key }}"
        dest: "/etc/ssl/private/{{ hpviz_vector_hostkey }}.key"
        mode: 0600
        owner: root
        group: root
      notify: restart nginx
      no_log: true
      ignore_errors: yes
      tags:
        - certificates

  handlers:
    - name: update trusted ca
      shell: /usr/sbin/update-ca-certificates
      tags:
        - skip_ansible_lint
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      ignore_errors: yes
