---
##################
## pb-deploy-docker.yml
##
## This playbook deploys and manages docker services on the viz group of servers
##
- name: Manages remote users
  hosts: viz:!localhost
  gather_facts: yes
  become: True

  roles:
    - role: geerlingguy.docker
