---
- name: deploy nginx reverse proxy
  hosts: viz
  become: true

  pre_tasks:

   - name: Create nginx private key folder.
     file:
       path: /etc/ssl/private
       state: directory
       owner: root
       group: root
       mode: 0700

   - name: Copy public certificate to nginx SSL configuration folder.
     copy:
       content: "{{ hpviz_tls_cert }}"
       dest: '/etc/ssl/certs/{{ hpviz_vector_hostkey }}.crt'
       mode: 0640
       owner: root
       group: root
     notify: restart nginx
     ignore_errors: yes

   - name: Copy private key to SSL configuration folder.
     copy:
       content: "{{ hpviz_tls_key }}"
       dest: '/etc/ssl/private/{{ hpviz_vector_hostkey }}.key'
       mode: 0600
       owner: root
       group: root
     notify: restart nginx
     no_log: true
     ignore_errors: yes

  roles:
    - role: geerlingguy.nginx
