---
- name: deploy nginx reverse proxy
  hosts: viz
  become: true

  pre_tasks:
    - name: Create nginx private key folder.
      file:
        path: /etc/ssl/private
        state: directory
        owner: root
        group: root
        mode: 0700
      tags: nginx

    - name: Copy public certificate to nginx SSL configuration folder.
      copy:
        content: "{{ hpviz_tls_cert }}"
        dest: "/etc/ssl/certs/{{ hpviz_vector_hostkey }}.crt"
        mode: 0640
        owner: root
        group: root
      notify: restart nginx
      ignore_errors: yes
      tags: nginx

    - name: Copy private key to SSL configuration folder.
      copy:
        content: "{{ hpviz_tls_key }}"
        dest: "/etc/ssl/private/{{ hpviz_vector_hostkey }}.key"
        mode: 0600
        owner: root
        group: root
      notify: restart nginx
      no_log: true
      ignore_errors: yes
      tags: nginx

  roles:
    - role: geerlingguy.nginx
      tags: nginx

  tasks:
    - name: Install latest passlib with pip
      pip: name=passlib
      tags: nginx

    - name: provision nifi users
      htpasswd:
        path: /etc/nginx/nifi.htpasswd
        name: "{{ hpviz_nifi_admin_user }}"
        password: "{{ hpviz_nifi_admin_pass }}"
        # owner: root
        # group: root
        # mode: 0640
      tags: nginx

    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      ignore_errors: yes
      tags: nginx
