---
##################
## pb-install-packages.yml
##
## This playbook installs the required packages on the remote services
##
- name: Install packages
  hosts: viz:!localhost
  gather_facts: yes
  become: True

  roles:
    - role: geerlingguy.docker

- name: Install packages
  hosts: sink:!localhost
  gather_facts: yes
  become: True

  roles:
    - role: geerlingguy.docker