---
######################
## site.yml
##
##  defines HPViz Project site-wide play-book workflow

- name: import pb-common.yml
  import_playbook: pb-common.yml

- name: import pb-users.yml
  import_playbook: pb-users.yml

- name: import pb-install-packages.yml
  import_playbook: pb-install-packages.yml

- name: import pb-docker-deploy-viz.yml
  import_playbook: pb-docker-deploy-viz.yml

- name: import pb-docker-deploy-sink.yml
  import_playbook: pb-docker-deploy-sink.yml

- name: import pb-deploy-nginx.yml
  import_playbook: pb-deploy-nginx.yml

- name: import pb-sink_data.yml
  import_playbook: pb-sink_data.yml