# Production configuration changes for docker-compose.yml are to be placed here.
# Solely used to push any configs that are desirable for prod

services:

  nginx-proxy:
    restart:
      - always
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html           
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from: nginx-proxy
    environment:
      - DEFAULT_EMAIL= ["lburciu@our.ecu.edu.au", "screaton@our.ecu.edu.au"]
  
  broker:
    environment:
      - NETWORK_ACCESS=internal

  connect:
    environment:
      - NETWORK_ACCESS=internal

  schema_registry:
    environment:
      - NETWORK_ACCESS=internal

  ksqldb-server:
    environment:
      - NETWORK_ACCESS=internal

  ksqldb-cli:
    environment:
      - NETWORK_ACCESS=internal
  
  elasticsearch:
    environment:
      - NETWORK_ACCESS=internal
  
  rest-proxy:
    environment:
      - NETWORK_ACCESS=internal

  neo4j:
    depends_on: 
      - nginx-proxy
    expose:
      - "17474"
    environment:
      - VIRTUAL_HOST=neo4j.viz001.ecu-sri.net
      - LETSENCRYPT_HOST=neo4j.viz001.ecu-sri.net
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=17474

  nifi:
    depends_on: 
      - nginx-proxy  
    expose:
      - "9090"
    environment:
      - VIRTUAL_HOST=nifi.viz001.ecu-sri.net
      - LETSENCRYPT_HOST=nifi.viz001.ecu-sri.net
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=9090      

  grafana:
    depends_on: 
      - nginx-proxy  
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=grafana.viz001.ecu-sri.net
      - LETSENCRYPT_HOST=grafana.viz001.ecu-sri.net
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=3000

  dejavu:
    depends_on: 
      - nginx-proxy  
    expose:
      - "1358"  
    environment:
      - VIRTUAL_HOST=dejavu.viz001.ecu-sri.net
      - LETSENCRYPT_HOST=dejavu.viz001.ecu-sri.net      
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=1358     