[sources.syslog_thesink]
  # syslog from thesink via vector
  # General
  type = "vector" # Assuming the source is the Vector sink on 'thesink'
  address = "143.110.158.73:9000" # IP address of 'thesink'
  shutdown_timeout_secs = 30 # optional, default: 30s

  # TLS
  # Make sure to mount volume in docker-compose '/etc/ca-certificates/certificate_authority.crt:/etc/ssl/certs/certificate_authority.crt'
  tls.ca_file = "/etc/ssl/certs/certificate_authority.crt" # Local to the vector container.
  tls.crt_file = "/etc/ssl/certs/host_certificate.crt" # as above
  tls.enabled = true
  tls.key_file = "/etc/ssl/certs/host_certificate.key" # as above
  tls.key_pass = "${KEY_PASS_ENV_VAR}" # Configure GITHUB_SECRETS "KEY_PASS_ENV_VAR" !! - This needs to be configured on ansible
  tls.verify_certificate = true

[sources.syslog_viz001]
  # syslog from viz001 (localhost)
  type = "syslog" # required
  mode = "unix" # required, options 'udp', 'tcp', 'unix'
  path = "/var/log/syslog" # required, required when mode = "unix"


[sinks.kafka]
  # General
  type = "kafka" # required
  inputs = ["syslog_thesink", "syslog_viz001"] # Format: "[sources.foo]", "[sources.bar]" == ["foo", "bar"]
  bootstrap_servers = "broker:29092" # required - need to test if it will accept a hostname vs just IP address
  compression = "none" # optional, default
  healthcheck = true # optional, default
  key_field = "user_id" # required
  message_timeout_ms = 300000 # optional, default
  socket_timeout_ms = 60000 # optional, default
  topic = "topic-1234" # required

  # Advanced
  #librdkafka_options."client.id" = "${LIBRD_KAFKA_ENV_VAR}" # example: Configure GITHUB_SECRETS "LIBRD_KAFKA_ENV_VAR" !!
  #librdkafka_options."fetch.error.backoff.ms" = "1000" # example
  #librdkafka_options."socket.send.buffer.bytes" = "100" # example

  # Buffer
  buffer.max_events = 500 # optional, default, events, relevant when type = "memory"
  buffer.max_size = 104900000 # required, bytes, required when type = "disk"
  buffer.type = "memory" # optional, default
  buffer.when_full = "block" # optional, default

  # Encoding
  encoding.codec = "text" # optional, default
  encoding.except_fields = ["timestamp", "message", "host"] # optional, no default
  #encoding.only_fields = ["timestamp", "message", "host"] # optional, no default
  encoding.timestamp_format = "rfc3339" # optional, default

  # SASL
  # sasl.enabled = true # optional, no default
  # sasl.mechanism = "SCRAM-SHA-256" # optional, no default
  # sasl.password = "password" # optional, no default
  # sasl.username = "username" # optional, no default

  # TLS
  # Make sure to mount volume in docker-compose '/etc/ca-certificates/certificate_authority.crt:/etc/ca-certificates/certificate_authority.crt'
  tls.ca_file = "/etc/ca-certificates/certificate_authority.crt" # Local to the vector container.
  tls.crt_file = "/etc/ca-certificates/host_certificate.crt" # as above
  tls.enabled = true
  tls.key_file = "/etc/ca-certificates/host_certificate.key" # as above
  tls.key_pass = "${KEY_PASS_ENV_VAR}" # Configure GITHUB_SECRETS "KEY_PASS_ENV_VAR" !! - This needs to be configured on ansible
  tls.verify_certificate = true
