---
# Base project directory
hpviz_base_dir: /opt/hpviz

# These are users specific to "viz" group of hosts
#  1) To remove a user from all groups replace the group list with empty string ''
#  2) Removing users change 'state: absent'  all theire directories will eb removed
#  3) pub_key must be present
#  4) all users are created with password login disabled
user_list:
  - username: hpviz-ci
    comment: "WARNING removing this user will break HPViz project CI"
    state: present
    shell: "/bin/bash"
    groups:
      - wheel
    pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsAK7JA+lFIAm9Wnj6x1graKajCi9Sis2M8gwDktRZ8sEPAK7ifFFvkG3T9jDTCnE9FXp6IaLtJlhsg5fqOFcJdwYtadyuCOoTGxL7SrPc5Kze9NbQJYNbXQPc6VQop04Rbj5eeh+kjpr0C8PAPw/lvOksKwIqqvZ5HykdQ7OXiP1WBCaA8bh6hEoi0+zMGem5/hOyWCkqtf3dnUC/2GPbTW8qSBzQxJpaQnMcnw/8dDYEDxQ9FC5m4j8cL/Ol1JIR8f3T5La2T990v18y/LY8JmNF7xsKqec6C2ImWmOKEMlUPUhN8BJLFPgTnAaR3JTVbQHMVukITDNRF+QmTipsUZfQnnnGjwtvuuPqu8ZQjue9itEQBEk7l+aC6ZRfyoEErWLownSDNG3lAqaQb+7qoTwOPrV7/ifeRX/8sEzyQERRaZXbPOv0ZFl2IyCUoq3FXKVlukDBv6zYwEqzQmRlCXK9E4SxCttur9RieGxHiDNEaBG26mvAEnrlpuFWs99SUuh0Jbu+e2bQhL8veR1p3iyLYGZ6YEE/jhe4ViyMlVNEmnrGuuTS229SDpykr+YLKhd42ND7b5WdEL9R47UzzuFdXvkk9Zv7KZ8TgOOwg4xMGmi4LH2phqc8NjxusLwJedmREQSs85YT3zOlHU1g7SIJx1dadRkTUz/XOEPDAQ== hpviz-ci"

### Managed pip packages to install
pip_install_packages:
    - name: docker
    - name: docker-compose

### Firewall - defaults to tcp
firewall_services:
  - name: ssh     # <- Do no remove will break CICD
  - name: https
  - name: 522
  - name: 9093    # kafka broker listener
  - name: 9090

# Syslog
hpviz_syslog_ingest_ip: 127.0.0.1
hpviz_syslog_ingest_port: 514

#grafana

hpviz_grafana_admin_pass: "{{ vault_hpviz_grafana_admin_pass }}"

## NGINX Reverse proxy config
nginx_vhosts:
  - listen: "443 ssl"

    server_name: "{{ hpviz_virtual_hostname }}"

    extra_parameters: |
      location /grafana/ {
          proxy_pass http://127.0.0.1:3000/;
          proxy_set_header   Host $host;
      }

      ssl_certificate /etc/ssl/certs/{{ hpviz_vector_hostkey }}.crt;
      ssl_certificate_key /etc/ssl/private/{{ hpviz_vector_hostkey }}.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
      client_max_body_size 25m;

# Redirect HTTP traffic to HTTPS
  - listen: "80"
    server_name: _
    return: "301 https://$host$request_uri"
