---
- name: Converge
  hosts: all

  tasks:
  - name: Update apt cache (On Ubuntu)
    apt:
      update_cache: true
      cache_valid_time: 3600
    when: ansible_os_family =="Ubuntu"

- import_playbook: ../../site.yml
