---
# TLS certificates for this host
hpviz_tls_cert: '{{ vault_hpviz_tls_cert }}'
hpviz_tls_key: '{{ vault_hpviz_tls_key }}'

# vector
hpviz_vector_hostkey: "thesink_ecu-sri_net"

hpviz_syslog_ingest_ip: "127.0.0.1"
hpviz_syslog_ingest_port: "1514"

# IP Addresses
hpviz_sink_ip: "{{ vault_hpviz_sink_ip }}"
hpviz_viz_ip: "{{ vault_hpviz_viz_ip }}"
hpviz_vector_port: "9000"
