---
# handlers file for firewall

- name: reload firewall
  ansible.builtin.service:
    name: "{{ firewall_service }}"
    state: reloaded
  when:
    - ansible_connection != "docker"
    - not ansible_check_mode | bool

- name: reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
