---

#
# Resources:
#   https://galaxy.ansible.com/docs/contributing/importing.html
#   https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#travis-integrations
#   https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
#
language: python
python: "2.7"

# Use the new container infrastructure.
sudo: false

before_install:
  # Make sure everything is up to date.
  - sudo apt-get update -qq
  - sudo apt-get install wget python-pip

install:
  # Inspect build environment resources.
  - free -h
  - df -h

  # Install Ansible.
  - pip install ansible

  # Check ansible version.
  - ansible --version

  # Add ansible.cfg to set up roles path.
  - wget https://gist.githubusercontent.com/honzamach/a7ea8ee0250c4adef91306f1d1629869/raw/e69e096cbd2529750fa115ee70c5438247f14410/ansible.cfg

  # Or alternative option: Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../' >ansible.cfg

  # View and verify contents of test ansible.cfg file.
  - cat ansible.cfg

script:
  # Check YAML syntax.
  - ansible-playbook -v -i tests/inventory tests/test.yml --syntax-check

notifications:
  # Notify Ansible Galaxy to pull role after successfull build.
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
